name: Build and push to default branch

on:
  push:
    branches-ignore:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN || github.token }}
      - name: Rebase branch
        run: |
          git rebase origin/master
      - name: Build code
        uses: gradle/gradle-build-action@v2
        with:
          args: build
      - name: Push branch
        run: |
          git push origin master
      - name: Push changes to default branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
